### ISSUE TITLE
Add option to start signaltower only on localhost

### ISSUE THREAD

**Issue by farao** [palavatv/signaltower#15]
Currently the signaltower starts on all network hosts (0.0.0.0 in netstat) and this should stay the default. Nevertheless, an option to start only on localhost, e.g. when the signaltower is begin a reverse proxy like nginx, is needed as a configurable option, e.g. SIGNALTOWER_LOCALHOST=y.

**Comment by janlelis** [comment]
I think this is a useful feature. Some points that come to my mind:
- For some configurations, it might also be useful to bind to a local network address only
- Lets discuss, if it would also be a sensible default to bind to localhost, with explicit README examples how to start it on a public ip? This would prevent accidental "open" signaltower instances

**Comment by erikzenker** [comment]
You can assign the issue to me

**Comment by erikzenker** [comment]
I provided a pull request #23. We could use the PR to discuss about the issue.

**Comment by farao** [comment]
Fixed by pr #23
