### ISSUE TITLE
Send shutdown event when shutting down

### ISSUE THREAD

**Issue by farao** [palavatv/signaltower#20]
When the signal tower is shut down, according to the palava protocol a shutdown event shall be sent:
```
{
  event: 'shutdown'
}
```

**Comment by farao** [comment]
This should have a test (especially since I'm not 100% sure if the events will "make it out" before the application is killed). I added another issue for adding integration tests: https://github.com/palavatv/signaltower/issues/26

**Comment by janlelis** [comment]
Also, the old version had the following behavior: it had the number of seconds before a (scheduled) shutdown happens: https://github.com/palavatv/palava-web/blob/f9a64e686eb5e1bba8d50b9b32bac76d8cac9e69/src/views/Room.vue#L97-L100

palava-machine, listened to sigterm with a default shutdown time:
- https://github.com/palavatv/palava-machine/blob/cafea6361aceb4f3c1222b973272a48939da65c8/lib/palava_machine/server/core_events.rb#L40-L42
- https://github.com/palavatv/palava-machine/blob/b783c56cb4341a9189243d8d07e7076ce6e16a18/lib/palava_machine/server/core_support.rb#L34-L46
- https://github.com/palavatv/palava-machine/blob/cafea6361aceb4f3c1222b973272a48939da65c8/lib/palava_machine/runner.rb#L32

But, maybe that's also too much goldplating :neutral_face:

**Comment by farao** [comment]
Yeah, I think I would leave that out and rather not let a shutdown/restart of the palava server happen too often :D
